---
deployment:
  tasks:
    # Set the deployment path
    - export DEPLOYPATH=/home/codeblue/public_html/

    # Copy main.js
    - /bin/cp src/main/main.js $DEPLOYPATH

    # Copy the home.ejs view
    - /bin/cp src/views/home.ejs $DEPLOYPATH

    # Copy CSS files recursively
    - /bin/cp -R src/public/styles $DEPLOYPATH

# ---
# deployment:
#   tasks:
#     - export DEPLOYPATH=/home/codeblue/public_html/
#     - rsync -av --exclude 'node_modules' ./ $DEPLOYPATH/
#     - cd $DEPLOYPATH && npm install
